function love.conf(t)
    t.identity = "windmill"             -- Name of the save directory (string)
    t.appendidentity = true             -- Search in source directory (boolean)
    t.version = "11.0"                  -- LÖVE version (string)
    t.console = false                   -- Console (boolean, Windows only)
    t.gammacorrect = true               -- gamma-correct rendering (boolean)
 
    t.window.title = "windmill"         -- The window title (string)
    t.window.icon = nil                 -- Filepath as the window's icon(string)
    t.window.width = 800                -- The window width (number)
    t.window.height = 600               -- The window height (number)  
    t.window.borderless = false         -- Remove borders from window (boolean)
    t.window.resizable = false          -- user-resizable window (boolean)
    t.window.minwidth = 800             -- Minimum window width (number)
    t.window.minheight = 600            -- Minimum window height (number)
    t.window.fullscreen = false         -- Enable fullscreen (boolean)
    t.window.fullscreentype = "desktop" -- "desktop" fullscreen or "exclusive"
    t.window.vsync = 0                  -- Vertical sync mode (number)
    t.window.msaa = 16                  -- multi-sampled antialiasing (number)
 
    t.modules.audio = true              -- Enable the audio module (boolean)
    t.modules.data = true               -- Enable the data module (boolean)
    t.modules.event = true              -- Enable the event module (boolean)
    t.modules.font = true               -- Enable the font module (boolean)
    t.modules.graphics = true           -- Enable the graphics module (boolean)
    t.modules.image = true              -- Enable the image module (boolean)
    t.modules.joystick = true           -- Enable the joystick module (boolean)
    t.modules.keyboard = true           -- Enable the keyboard module (boolean)
    t.modules.math = true               -- Enable the math module (boolean)
    t.modules.mouse = true              -- Enable the mouse module (boolean)
    t.modules.thread = true             -- Enable the thread module (boolean)
    t.modules.window = true             -- Enable the window module (boolean)
    math.randomseed(os.time())          -- Generates a seed (based on the time)

end
